# syntax=docker/dockerfile:1.7
FROM python:3.14.7-alpine AS backend

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1 
ENV INSTANCE_CHANGELOG_URL https://sites.plane.so/pages/691ef037bcfe416a902e48cb55f59891/

RUN apk --no-cache add \
    "bash~=5.3" \
    "libpq" \
    "libxslt" \
    "nodejs-current" \
    "xmlsec" \
    "libffi-dev" \
    "g++" \
    "gcc" \
    "cargo" \
    "git" \
    "make" \
    "postgresql-dev" \
    "libc-dev" \
    "linux-headers"

WORKDIR /code

COPY requirements.txt ./requirements.txt
ADD requirements ./requirements

# Install the local development settings
RUN --mount=type=cache,id=pip-cache,target=/root/.cache/pip pip install -r requirements/local.txt --compile


COPY . .

RUN mkdir -p /code/plane/logs
RUN chmod -R +x /code/bin
RUN chmod -R 777 /code


# Expose container port and run entry point script
EXPOSE 8000

CMD [ "./bin/docker-entrypoint-api-local.sh" ]

